services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: plantepasser_db
    networks:
      - plantepasser_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PLANTEPASSER_DB_NAME}
      - MYSQL_USER=${PLANTEPASSER_DB_USER}
      - MYSQL_PASSWORD=${PLANTEPASSER_DB_PASSWORD}
    volumes:
      - db_data:/config     
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: plantepasser_backend
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - plantepasser_net
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PLANTEPASSER_DB_PASSWORD=${PLANTEPASSER_DB_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://plantapi.mandingo.dk
    container_name: plantepasser_frontend
    restart: unless-stopped
    networks:
      - plantepasser_net
    ports:
      - "8080:80"
    depends_on:
      - backend

networks:
  plantepasser_net:
volumes:
  db_data: